### ISSUE TITLE
Finding the "owner"?

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#10]
Prior to my comment below, I acknowledge the following paragraph:

<img width="949" alt="Screenshot 2020-10-09 at 13 26 53" src="https://user-images.githubusercontent.com/3274335/95577800-211b9e00-0a33-11eb-9e2d-33b58e9c6ca7.png">

It is mentioned that this system is not only envisioned with respect to locations, but also more complex situations. 

A positive user is expected to inform the contact tracing authorities of their recent activities. Somehow the authorities are expected from this to find the "owner". It looks to me as if there is a missing step there: imagine I attend 10 protests in past 14 days, then test positive. How can authorities or I find the owners? This is especially puzzling in the cases where I have opted to use the paper-based solutions. 

Even if "finding the owner" is not part of the intent of the system, it is weird to justify introducing a lot of complexity in the whole system because of non-venue contexts (e.g. sensitive events) while at the same time essentially setting up the contact tracing process for failure for each non-sensitive context. It looks like this is very much looking for a globally satisfactory technological answer that will actually fail in most cases. 

At the very least this should be discussed, as there are non-technological alternatives. I observe for instance that AFAIK in Geneva political events are explicitly excluded from obligations to log.

**Comment by wouterl** [comment]
What events should enable notification is a policy decision orthogonal to CrowdNotifier.

CrowdNotifier provides the means for notifying users provided the “owner” can be contacted.  This is a limitation inherited from current schemes, which also require the owner to obtain access to the list of attendees (on paper or digital). In this systems it is implicitly assumed that the SARS-CoV-2-positive person has the means to either provide contact details for the owner, or information to find them (e.g., in a demonstration the organizer could provide a name, address, or telephone together with the QR-code).

If the owner cannot be (or wishes not to be) found, CrowdNotifier cannot be used in its current form. We do not consider this a limitation, but a feature, that enables “owners” to refuse to participate in the system if their activity is too sensitive.
