### ISSUE TITLE
Understandability of QR code content

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#12]
It would be good to include some discussion of the QR codes' understandability.

In particular I would expect people to by default not trust a QR code encodes what it says it encodes. If others would be capable of re-generating the QR-code, this would be helpful to generate trust. However my understanding is that this would require revealing the `notification_key`, whose secrecy seems to me to be pointless (see #11)

**Comment by wouterl** [comment]
The content of the QR code and its understandability is an important point under deployment, but it is out of the scope of this document.
