### ISSUE TITLE
Why a QR_tracing code?

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#14]
I am not certain to understand why a QR code is used for QR_tracing, given the obvious downsides of increased complexity (training, mistakes, lost tracking code, etc). 

I can see two reasons:
* it makes it independent of an app, which an owner might delete/change in the epidemiologically relevant interval
* multiple employees could act as "owners", through processes decided in a decentralized way (for instance the QR code could be kept in the safe of a venue) and in a robust way in the face of complexity ("who is the owner on call if I go on holiday?")

**Comment by wouterl** [comment]
There is no question to address.

**Comment by pdehaye** [comment]
The title of the GitHub issue is "Why a QR_tracing code?". I offer two possible reasons. A secondary question would be "is it because of one, two of those reasons?".

**Comment by wouterl** [comment]
We assumed the question was rhetoric. Both of them are good reasons.
