### ISSUE TITLE
Clarify what you mean by voluntary/mandatory

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#15]
There are many layers where presence tracing can be made voluntary/mandatory. 

For instance, it could be made mandatory that some venues collect information but that it would be voluntary for individuals to use a digital system themselves, while still retaining the obligation for the venue owner to register digitally the person into a system. 

There is a wide space of options, and it should be made clear which you consider, especially given that they have very different epidemiological motivations and impacts. 

I note for instance that while the system is described as "voluntary":
* Charlie starts using the system because he wants to "comply with regulations"
* "Attendees have a choice to use their app or not. If they do not, they, for instance, write their name" --> this seems to imply attendees have some obligation. Clarity here would be helpful as well: what if the venue owner has the obligation to verify the phone number/name? And so on.

**Comment by wouterl** [comment]
The obligatory nature of the system is a policy decision orthogonal to the design. 

This is a running example. We can add “for instance” for the owner, which is already explicit for the attendees. CrowdNotifier does not prescribe the fallback. We propose a pen&paper design but the fallback could be nothing if there is no obligation.

Just like for proximity tracing, we advocate that apps (and the use of phones) should not be obligatory. Similarly, a legal framework should ideally be put in place to ensure fundamental rights and to mitigate unexpected outcomes, risks and harms.
