### ISSUE TITLE
Compare privacy risks of ExposureNotification and CrowdNotifier

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#16]
In many countries it would be important to be able to compare ExposureNotification and CrowdNotifier risks, for multiple reasons:
* should CrowdNotifier be rolled out? 
* should the local ExposureNotification app be stopped?
* should we roll out CrowdNotifier instead of ExposureNotification
* etc

Of course considerations around epidemiological utility will come into play, and this is clearly not in scope of this White Paper. Nevertheless privacy and security risks will also enter into consideration, so a comparison of risks between ExposureNotification and CrowdNotifier should be included in this paper.

**Comment by wouterl** [comment]
This white paper evaluates the security and privacy risk of CrowdNotifier and comparable systems. A comparison between exposure notification and presence tracing is out of scope.
