### ISSUE TITLE
Share raw files

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#2]
The White Paper is currently shared as a .pdf. 

Please also include source files in raw format to enable easier comparison.

**Comment by carmelatroncoso** [comment]
We will do when the next version is uploaded. Will leave the issue open as a reminder.

**Comment by ineiti** [comment]
Done here: https://github.com/CrowdNotifier/whitepaper-internal

**Comment by pdehaye** [comment]
Link not working  :(

**Comment by carmelatroncoso** [comment]
Oops, internal misunderstanding. We'll make a repo with raw format publicly available soon.

(still leaving open as a reminder)

**Comment by wouterl** [comment]
The source of the whitepaper is now available [here](https://github.com/CrowdNotifier/whitepaper-sourcefiles). Thanks for everybody's patience.
