### ISSUE TITLE
Seem’s that canton requirement are not matched

### ISSUE THREAD

**Issue by TeoGoddet** [CrowdNotifier/documents#20]
A central presence database is currently in place for vaud. 

A major requirement that appeared during the discussion was that they need to be able to trigger the notification by themselves for a given venue (also they may need to be able to customize the message btw legal quarantine and renforced self surveillance)

Paper cannot be an option when numeric is available, because tracing capacities are not big enough to handle paper.
So venue should record on a digital database the entry of people without a phone

It seem that canton may also need the list of people they put in quarantine to control the quarantines they ordered (at least monitor).

Finally, this app (with a solution for non smartphone users) can be mandatory for someone to go in a venue (as people have choice to go or not to the venue)

**Comment by TeoGoddet** [comment]
About the interaction with the organizer/owner : tracing was made impossible at some point because disco owner did not answer to calls from the canton because sleeping during the working hours of the tracers.

That’s why a model without interaction with the venue should be considered

**Comment by carmelatroncoso** [comment]
Thanks for the comments and the pointers. 

Our design did not aim to be canton or Switzerland-specific, but an example of how QR-code-based tracing can be done in a privacy-preserving and abuse-preventing manner.

Indeed for local deployment, it is required that legal and technical frameworks are aligned.
