### ISSUE TITLE
Paper needs greater focus on public health effectiveness

### ISSUE THREAD

**Issue by peterkwells** [CrowdNotifier/documents#21]
**Summary** 

The paper is framed from the perspective of privacy and security, with only occasional nods to public health effectiveness. This could lead to misplaced design priorities and, if implemented, this could undermine public health activities. Rather than public health effectiveness being an implicit goal, it should be made explicit throughout.

**Detail**

The introductory paragraph requests feedback on "security and privacy properties", it does not mention public health properties. This should be added with input explicitly sought from the public health community.

The motivations section does not mention improved public health as a motivation, the only reference is to, undefined, "genuine epidemiological goals" within the 'checks on power and population controls' section.

Improved public health should be a whole paragraph in the motivations section, for example this might reference the belief that more trustworthy solutions may be more likely to be used by the population and that privacy can, along with other factors, contribute to trustworthiness.

The overview section includes three design principles (privacy-by-design, purpose limitation by design and voluntary). These are useful principles but another design principle should be "effectiveness" or "meets public health needs". Otherwise a design could comply with the principles but be ineffective or even harmful in terms of public health.

**Comment by carmelatroncoso** [comment]
Thanks for the suggestion. We acknowledge that the health motivation is buried in the Executive summary because our starting point was that that a system of the sort would be built to help with pandemic contention. We can add a bullet point to the motivation to reiterate.
