### ISSUE TITLE
Change from digital first to manual first 

### ISSUE THREAD

**Issue by peterkwells** [CrowdNotifier/documents#22]
**Summary** 

The paper presents the CrowdNotifier protocol, and the digital solution it supports, as the primary service stating that a non-digital fallback must always be available and describing the digital setup and diagrams for digital activities in the walkthrough of the system, but not the non-digital setup. This should be repositioned to describe the existing manual services and show how CrowdNotifier augments it as an alternative option which users may choose if they find it to be trustworthy.

**Detail**

Existing manual services exist that support the public health needs of this protocol. While manual services may be able to be  improved by use of digital technologies, we must ensure both that until digital methods are proven reasonably effective that manual services take priority, and that manual services are always available for those who choose/need to take them.

**Comment by TeoGoddet** [comment]
Written list of contact are useless, they are too much paper to handle for a growing number of Canton. That’s why they made apps with centralized database mandatory. (VD , BE, ...)
So what do you mean by manual ?

**Comment by peterkwells** [comment]
Hi Teo - 'useless' is a strong word. This protocol is not about tracing contacts it is about presence tracing, ie recording the presence of people at locations and then notifying them (under certain circumstances).

In the absence of digital solutions that type of presence recording/notification is performed manually with the list kept within the location and used when needed. For example, a hotel might decide to notify guests if a staff member tests positive an informs the hotel, or a public health authority might learn from a contact tracing process that an infected person works at a hotel, contact that hotel, and then determine/agree what notification activities should occur. This is already happening in multiple countries, and has happened in multiple previous pandemics.

The CrowdNotifier protocol is meant to augment these types of processes, that makes it quite useful to know what they are and to build on/with what already exists

**Comment by TeoGoddet** [comment]
Hi, my point was just that canton Vaud (at least) forbid paper list for (except if no mobile network is available at the location) because they cannot handle those list regarding the number of case everyday (they wan't to copy/paste number list in their SMS tool)

**Comment by pdehaye** [comment]
In Canton Geneva the difficulties around paper lists are stated to be twofold: validation of the phone number and speed at which phone numbers can be obtained in an effective form from the venue afterwards, once there is an incident. 
If a restaurant just hands out paper, the result is that very often they either had 5 Mickeys and 2 James Bond as clients at the same time, or that noone can read that Disney character's phone number. 
Part of a solution in some Geneva solutions is to already have the obligation for the restaurant to:
1/ validate number and/or ID
2/ make the data ready electronically 
but without imposing the obligation for the client to interact with the electronic solution (e.g. customer *writes* the data on Post-It, the data is immediately entered into electronic system and the Post-It is discarded afterwards). 

I like your original framing of the issue, @peterkwells, but it seems to me that you are missing context on the developments here in Switzerland, where the default has essentially switched to being electronic (partly justified via effectiveness reasons, as explained above)

**Comment by peterkwells** [comment]
Ah, that local context makes sense. Part of the challenge of defining global protocols! Thank you both for helping me to understand it :)

**Comment by carmelatroncoso** [comment]
Thanks for the suggestion. As we mention in #21 we take as starting point that, for the reasons mentioned in these answers or others, a digital solution would be put in place and provide an alternative that addresses privacy and abuse concerns.
