### ISSUE TITLE
Other approaches to presence tracing section misses existing manual processes & effectivenesses

### ISSUE THREAD

**Issue by peterkwells** [CrowdNotifier/documents#24]
**Summary**

The section comparing CrowdNotifier to other presence tracing approaches does not mention existing manual processes, which are deployed in all countries, and does not use public health effectiveness as a point of comparison.

**Detail**

Bringing in existing manual processes and comparing different measures on public health effectiveness would allow for discussion of how different section of the population will respond to or be affected by digital processes on smartphones. For example, access to smartphones or receptiveness to instructions to isolate/get tested that are delivered in text messages on smartphones rather than by public health officials.

**Comment by carmelatroncoso** [comment]
As explained in #21, we start from the assumption that a digital system will be put in place and study alternatives.

Nevertheless, we agree it is relevant to compare digital approaches' properties to that of manual processes. We will add this to the comparison.

The questions in the details are very important for deployment and should be carefully considered. They are however, out of the scope of this document.
