### ISSUE TITLE
Who does S2 protect against?

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#26]
The White Paper states:
<img width="745" alt="Screenshot 2020-10-13 at 23 04 22" src="https://user-images.githubusercontent.com/3274335/95916206-97f4c600-0da8-11eb-89ea-79184fb4012a.png">

Is the health authority an enemy to consider for S2? If it wanted to engage in population control, it could easily do so by sending a confederate to check-in and then marking that confederate as infected. 

So either S2 fails with respect to the health authority (not much that could be done I suspect, but it should be written) or it should be at least clarified which adversaries are considered re: S2 (I see "law enforcement" later).

**Comment by wouterl** [comment]
We will make explicit that in CrowdNotifier the health authority, as the users, needs to be trusted to not lie about infected users and the locations their visit. Note that the health authority doesn't even need to send somebody, they can just proceed as if somebody visited (as in the confused deputy example).
