### ISSUE TITLE
fallback (pen & paper) system doesn't need name

### ISSUE THREAD

**Issue by dkg** [CrowdNotifier/documents#28]
the "fallback system" description says:

> Every visitor enters contact information (e.g., name and phone number) into the box/list.

It's not clear that a contact tracer needs the user's name here -- what they need is the ability to contact the user.  I'd recommend offering any contact method: phone number or e-mail address  would be fine.

To the extent that people share phones or e-mail addresses, they are likely to also know who among the sharers was present at the given event.  We don't want this specification to be read to justify more intrusive "manual" surveillance than necessary.

(i grant that contact info is typically at least as identifying as name is; but people can establish ephemeral contact identifiers for these purposes if they want to, whereas they can't change their names)

**Comment by carmelatroncoso** [comment]
We agree. We will remove the name from the text to give a minimal data example.
