### ISSUE TITLE
fallback (pen & paper) system should acknowledge risk of transmissibility

### ISSUE THREAD

**Issue by dkg** [CrowdNotifier/documents#29]
I know the point of the CrowdNotifier proposal is *not* the fallback system -- but the fallback system needs to be plausible for the paper as a whole to be plausible.

Saying "pen and paper" without more precautions introduces a potential vector for disease transmission, if pens and paper are used.  It wouldn't hurt to include a couple of sentences about avoiding pen reuse without first sanitizing, and ensuring that the contact info can be deposited "in the box" via some low-touch mechanism.

it would be a shame if the fallback notifier system was itself the leading cause of a spreading event where people were otherwise mainly socially distanced!

**Comment by carmelatroncoso** [comment]
The implementation of the pen & paper solution and its safety is an important point under deployment, but it is out of the scope of this document.
