### ISSUE TITLE
Compare with existing peer-reviewed research

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#3]
"Existing presence tracing systems do so at the sole discretion of a central authority such as a public health agency"

This is not quite true. There are older proposals, such as [this one](https://mhealth.jmir.org/2020/4/e18936/). 

It would be helpful to compare this new proposal to existing peer-reviewed research.

**Comment by wouterl** [comment]
We meant systems deployed at scale with some notion of data minimization, but will clarify the statement to be a bit more precise.

Comparison with all existing systems, in particular systems that are not deployed, is for now out of the scope of the current document.
