### ISSUE TITLE
? "entry QR code QR_exit" should be "exit QR code QR_exit"?

### ISSUE THREAD

**Issue by Thusid** [CrowdNotifier/documents#30]
In "CrowdNotifier, Decentralized privacy-preserving presence tracing, Version 8 October 2020", page 13 the text reads:

> 2. A page that includes the entry QR code QR_exit, with clear instructions.

Shouldn't this read:

> 2. A page that includes the **exit** QR code QR_exit, with clear instructions.

**Comment by wouterl** [comment]
Good catch! Will fix in the next version. Thanks!
