### ISSUE TITLE
What is a "classic" system? A "privacy-preserving digital solution"?

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#5]
The past few months have seen a wide array of systems be implemented, with many labeling themselves as "privacy-preserving" and digital. Given this, what is a "classic" system? 

The following paragraph, for instance, packs a multitude of assumptions about what "classic" systemS and "privacy preserving digital systems" do that do not seem to match my assessment of what currently deployed systems do. 
<img width="963" alt="Screenshot 2020-10-09 at 12 45 20" src="https://user-images.githubusercontent.com/3274335/95574628-91bfbc00-0a2d-11eb-8382-224b460a69d3.png">

**Comment by wouterl** [comment]
We acknowledge “classic” is ambiguous. We will clarify. We will not clarify assumptions that are not essential for a high-level introduction.
