### ISSUE TITLE
Why not use the GAEN framework?

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#6]
<img width="971" alt="Screenshot 2020-10-09 at 13 35 02" src="https://user-images.githubusercontent.com/3274335/95578518-4b219000-0a34-11eb-9663-a52104af45fe.png">
At least one of the authors of this paper has testified in the UK Parliament that everything that could be done with a centralized solution could be done with DP-3T's model as of ~June 2020. 

How does that square with the screenshot above? 

However, reasons not to use the GAEN framework include:
1. The GAEN framework is not sufficiently secure or privacy-preserving compared to its utility. Hence decoupling the two will make it easier for civil society actors to recommend adoption of the present protocol. 
2. contractual constraints around using the GAEN framework introduce sovereignty issues
4. this worsens inclusion issues, since some have a smartphone old enough not to be able to run the GAEN framework

These issues should be mentioned.

**Comment by wouterl** [comment]
In the current version we wanted to highlight the technical nature of the challenges and why other technology should be used.

Thanks for the suggestions. We will remark that the second and third are issues to take into account by deployers. The first is subjective, and policy-oriented, which is out of the scope of this document.

Finally, please respect the Code of Conduct and make this space nice. Please refrain from referring to people when this is not central to the point. (See also #4)

**Comment by pdehaye** [comment]
If the goal is to highlight the technical nature of the challenge, it might make more sense to compare directly to DP-3T or more generically Bluetooth-based protocols, since GAEN comes with a lot of its own baggage irrelevant to the point you are making (hence indeed my 2nd and 3rd point). 

Bluetooth could be used as a medium for information exchange rather than QR-code, after all (and this might have benefits that would be valued above QR-codes in some deployment scenarios). 

It sounds like ultimately what you are arguing is that a Bluetooth-based solution (whichever it is) is in your view inadequate for NF2. 

<img width="953" alt="Screenshot 2020-10-16 at 22 45 35" src="https://user-images.githubusercontent.com/3274335/96307140-69255c80-1001-11eb-9433-5857274104ed.png">

I think you should say so more precisely.
