### ISSUE TITLE
Do not specify epidemiological variables

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#7]
<img width="630" alt="Screenshot 2020-10-09 at 13 45 29" src="https://user-images.githubusercontent.com/3274335/95579337-bc157780-0a35-11eb-8197-a3d30326a275.png">
No epidemiological argument has been offered why 10 is the right number. It actually most likely is not.

**Comment by wouterl** [comment]
This follows the approach of contact tracing apps and is easily modified if epidemiological requirements expose the need for a longer/shorter retention. Until then, 10 days seems a sane default. We will add a footnote to say that this number is orientative and up to the deployer of the system.

**Comment by pdehaye** [comment]
Epidemiological requirements do expose the need for longer retention, or at the very least the need to avoid uncritically transferring any assessment based on current understanding of contact tracing apps, as currently deployed. 

If this is not clear to the authors, **do not** assume the default would be the same, **do not** allow your text to improperly give that impression, and do run and ask an epidemiologist for advice on this matter. 

I do not think security researchers should not offer orientative values here, and do think epidemiologists should explain how they derive such an orientative value.
