### ISSUE TITLE
Please consider using another concept than "presence", such as "context"

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#8]
"Presence" evokes physical presence. This is actually, AFAICT, unnecessary in your presentation, except for two "touchpoints": someone has to scan a (presumably physical) QR-code, and there is a paper-based alternative to gain physical access to a venue/event. 

I suspect it would be more productive in multiple ways to talk about "context". You could present the protocol by talking about contexts abstractly, and then explain how this protocol would be realized when someone enters/exits a physical context. 

This brings two main interlocking benefits:
1/ You can talk about non-physical contexts, which can be much more abstract, but are essentially all higher dimensional mathematical constructs on top of the graph where edges are physical presence. An example I could think of would be "parents of kids in the same class" or "people who used this wastewater collection system". This leaves the door open to more generally interesting uses, if epidemiologically desirable (the notification need not lead to quarantine, depending on how the cohort was structured). 
2/ You can talk about a hierarchy of contexts, for instance floors in an office building or classes in a university program. 

See some of those ideas being prototyped here, in Canton Geneva:
https://github.com/PersonalDataIO/GEgraph

**Comment by wouterl** [comment]
CrowdNotifier is not limited to physical locations, as we clarify in page 3

> Location: a semi-public location (for example, bar, restaurant, religious building, events venue, or meeting place) or an event which takes place in one or more locations (for example, a demonstration).

The name specifically focuses on the crowd, as it is having a crowd (the context is the crowd) that defines who should be notified. 

Anyhow, we appreciate the comment as we thought about the name a lot, but we did not find a better term. At this point in time we do not plan to change the terminology.
