### ISSUE TITLE
Ethical considerations in designing system in the face of potentially too extreme threats

### ISSUE THREAD

**Issue by pdehaye** [CrowdNotifier/documents#9]
A few restrictions on the system seem extremely conservative privacy wise, and do not balance considerations of culture or the current epidemiological situation (i.e. how dire things are in a certain location). They also introduce enormous complexity which will hinder adoption, if only because less people will trust the system because they don't understand it. 

Please explain your ethical approach to this problem, as it could potentially weaken trust to currently deployed systems that are in dire need in some places.

**Comment by wouterl** [comment]
We see that current approaches raise serious ethical concerns. This includes harassment and the [sale of collected data to third parties](https://www.thetimes.co.uk/article/contact-tracing-data-harvested-from-pubs-and-restaurants-being-sold-on-s0d85mkrr). Our work intends to raise awareness on the way in which these systems are not trustworthy and provide an alternative for discussion.

We provide a design and document its risks. Whether CrowdNotifier is too privacy-preserving for a given situation is a policy decision out of the scope of this document. 

Note that even if a less abuse-resistant or privacy-preserving solution is preferred, the document can still be used to document design decisions and explain risk / benefit trade offs.

**Comment by pdehaye** [comment]
Security researchers have long accepted the need to take into account ethical processes in disclosing vulnerabilities of running systems, as this public disclosure would undermine the security of running systems. A mitigation measure would be, for instance, to privately signal to the deployer of such a system that there is a problem, and give some time to that system owner to fix the problem. 

In this work, you partly attract attention to valid secondary problems (privacy/abuse) with running systems, which some would consider as critical for protecting life. This might be the right move, but you had alternatives. You could have, for instance, worked with the owners of currently deployed systems to improve them. My question was around how you balanced this tension. 

I note however that the link you posted makes most of this moot (public trust is already eroded somewhat), but it appeared between my original question and your response.
